<?php

define('PINAUTH_TEST_SECRET', 'secret');

function pinauth_menu() {
  $items['pinauth/%/%'] = array(
    'title' => 'Final authentication',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pinauth_code', 1, 2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function pinauth_user($op, &$edit, &$account, $category = FALSE) {
  global $user;
  if ($op == 'login') {
    // First login operation, send to pinauth form.
    // @todo is session best for storing whether pinauth was valid?
    // @todo user roles permission based pinauth?
    if (!$_SESSION['pinauth_code']) {
      $uid = $user->uid;
      // Destroy the current session.
      session_destroy();
      module_invoke_all('user', 'logout', NULL, $user);
  
      // Force anonymous user.
      $user = user_load(array('uid' => 0));
      unset($_REQUEST['destination']);
  
      $signatory = db_fetch_object(db_query_range('SELECT * FROM {users} WHERE uid = %d', $uid, 0, 1));
      $login_hash = _pinauth_login_hash($signatory);
      drupal_goto('pinauth/' . $signatory->uid . '/' . $login_hash);
      // @todo could also form alter login forms to go multi-step?
    }
  }
}

/**
 *
 */
function _pinauth_login_hash($account) {
  // @todo consider timeouts and better hashing
  return md5($account->name . $account->pass . $account->login);
}

/**
 *
 */
function pinauth_code($form_state, $uid, $hash = NULL) {
  // Confirm hash is valid. @todo could account for timeouts.
  $account = user_load(array('uid' => $uid));
  $valid_hash = _pinauth_login_hash($account);
  if ($hash != $valid_hash) {
    drupal_access_denied();
    exit();
  }
  
  $form['uid'] = array(
    '#type' => 'value',
    '#value' => $uid,
  );
  $form['code'] = array(
    '#type' => 'textfield',
    '#title' => t('Code'),
    '#required' => TRUE,
  );
  $form['login'] = array(
    '#type' => 'submit',
    '#value' => t('Log in'),
  );

  return $form;
}

/**
 *
 */
function pinauth_code_validate($form, &$form_state) {
  // 
  if ($form_state['values']['code'] != PINAUTH_TEST_SECRET) {
    form_set_error('code', t('Invalid code.'));
    // @todo flood
  }
}

/**
 *
 */
function pinauth_code_submit($form, &$form_state) {
  global $user;

  $uid = $form_state['values']['uid'];
  $account = user_load(array('uid' => $uid));
  $edit = array();
  
  $user = $account;
  // Update the user table timestamp noting user has logged in.
  $user->login = time();
  db_query("UPDATE {users} SET login = %d WHERE uid = %d", $user->login, $user->uid);

  // Regenerate the session ID to prevent against session fixation attacks.
  sess_regenerate();
  $_SESSION['pinauth_code'] = TRUE; // @todo is session best for storing validation?
  user_module_invoke('login', $edit, $user);
  $form_state['redirect'] = 'user/' . $user->uid; // @todo destination
}
