<?php

/**
 * @file tfa_test.module.
 * A mock module for testing TFA.
 */

/**
 * Implements hook_tfa_api().
 */
function tfa_test_tfa_api() {
  return array(
    'tfa_test_login' => array(
      'class' => 'TfaTestLogin',
      'name' => 'Login test',
    ),
    'tfa_test_send' => array(
      'class' => 'TfaTestSend',
      'name' => 'Send test',
    ),
    'tfa_test_totp' => array(
      'class' => 'TfaTestTotp',
      'name' => 'TOTP test',
    ),
    'tfa_test_fallbase' => array(
      'class' => 'TfaTestFallback',
      'name' => 'Fallback test',
    ),
  );
}

function _tfa_test_set_context($account, $context) {
  $_SESSION['tfa'][$account->uid] = $context;
}
